app:
  run_mode: debug
  app_path:
  template_path: web/template
jwt:
  secret: wuweichao.com
  ttl: 43200
html:
  title: Share
  keywords: Share,Golang,Blog
  description: a minimalist style blog base on golang