database:
  type: mysql
  host: 127.0.0.1
  port: 3307
  user: root
  password: 123456
  dbname: share
  table_prefix:
  charset: utf8mb4
redis:
  host: 127.0.0.1
  port: 6379
  password: 1234561
  database: 0